language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
#  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
    - php: 7.1
   # - php: hhvm

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer update --dev --prefer-dist --no-interaction

before_script:
  - mysql -e 'create database yii2_translateable_test;'

script:
  - "wget http://codeception.com/php54/codecept.phar"
  - php ./codecept.phar build
  - php ./codecept.phar run --coverage --xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/_output/report.xml
